config:
  ul-style:
    style: dash
  ul-indent:
    indent: 2
  commands-show-output: false
  line-length: false
  no-duplicate-header: false
  header-increment: false
ignores:
  - '**/node_modules/**'
  - '**/dist/**'
  - CHANGELOG.md
showFound: true
noProgress: false
outputFormatters:
  - - 'markdownlint-cli2-formatter-pretty'
    - appendLink: true
